root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ."
bin = "tmp/main"
full_bin = "./tmp/main"
include_ext = ["go", "tpl", "env"]
exclude_dir = ["tmp", "vendor"]
include_dir = []
exclude_file = []
exclude_unchanged = true
log = "air.log"
delay = 100
stop_on_error = false
send_interrupt = true
kill_delay = 500

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true
